### ISSUE TITLE
Не полное воспроизведение текста готовой фразы

### ISSUE THREAD

**Issue by jely-scs** [AkmalArtikov/deaf#1]
Оборудование: Samsung Galaxy S2 / android 4.1.2
Сборка: 1 
Тип соединения: wifi
Шаги воспроизведения:
1) На экране с готовыми фразами нажимаем на фразу: "Я не слышу. Говорите, пожалуйста, в микрофон..."
2) Нажимаю на воспроизведение текста.
 Результат: воспроизведение фразы до слов: "Произносите слова медленно и разборчиво"
Ожидаемый результат: воспроизведение всего текста

**Comment by AkmalArtikov** [comment]
Тоже воспроизводится. Причем, если редактировать эту фразу, то она воспроизводится потом полностью

**Comment by AkmalArtikov** [comment]
Fixed
