### ISSUE TITLE
Длинная фраза подвешивает телефон

### ISSUE THREAD

**Issue by jely-scs** [AkmalArtikov/deaf#2]
Оборудование: Samsung Galaxy S2 / android 4.1.2
Сборка: 1 
Тип соединения с сетью: wifi
Шаги воспроизведения:
1) Открываем диалог
2) непрерывно говорим в течении нескольких минут, не давая закончить фразу

Результат: приложение зависает и крешится
Ожидаемый результат: буфер не переполняется. Возможны принудительное окончание фразы.

**Comment by AkmalArtikov** [comment]
У меня при достаточно длинной фразе Разговор сам обрубает ее, оборачивает в бабл и продолжает распознавание в следующем бабле. Не получилось воспроизвести

**Comment by AkmalArtikov** [comment]
Fixed
