### ISSUE TITLE
Креш приложения при неизвестной фразе

### ISSUE THREAD

**Issue by jely-scs** [AkmalArtikov/deaf#3]
Воспроизводится не стабильно!

Оборудование: Samsung Galaxy S3
Сборка: 1 
Тип соединения с сетью: wifi
Шаги воспроизведения:
1) Открываем диалог
2) Говорим несуществующее слово (например, быстро говорим абвгдезжклн)

Результат: приложение зависает и крешится
Ожидаемый результат: выводить какой-нибудь вариант, либо сообщение, что не смог распознать.

**Comment by AkmalArtikov** [comment]
Не получилось воспроизвести. Может, есть какие-то доп. условия?

**Comment by AkmalArtikov** [comment]
Fixed
