### ISSUE TITLE
Пропадает 3-я снизу запись

### ISSUE THREAD

**Issue by jely-scs** [AkmalArtikov/deaf#4]
Оборудование: Samsung Galaxy S3 / Lenovo A536 (скорее всего не зависит от телефона)
Сборка: 1 
Тип соединения с сетью: wifi
Шаги воспроизведения:
1) Открываем диалог
2) Создаем 2 любых фразы (не важно голосом, либо печатаем)
3) Голосом записываем 3-ю фразу, 
Результат: на экране 2 фразы, первую фразу не видно.
Если фраз больше, то не отображается только 3-я снизу фраза, остальные остаются. При перерисовке экрана, добавлении нового соощения все фразы появляются.
Ожидаемый результат: все фразы присутствуют на экране
На скриншоте отсутствует 2-я фраза.
![screen_phrase](https://cloud.githubusercontent.com/assets/1853038/12242181/57aad9a2-b8b9-11e5-8ed5-66cefa63aaee.png)

**Comment by AkmalArtikov** [comment]
Воспроизводится тоже на HTC One_M8, Android 5.1

**Comment by AkmalArtikov** [comment]
Fixed
